# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0a791ab92d5d513bba9b994fd9809a43a72b7cb09fd628b7121dd817e223361d705ba73be86442da26b43baaf4257d8b06b8eaf0be4772c0eaad558d0ccfc747

test:
  secret_key_base: 5f47b8b899aebf69e67e229d41e22d649faaebab5e709b1c72c744ea35d8514fe65297b6df0534d39010add8840ce4ecc15422826999d86f8babde30796f67e7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
